feat(nodejs): templates_only can be specified to skip generating index.ts
googleapis/synthtool pull request #1017
Opened 2021-04-02 00:16 UTC by bcoe

I noticed that https://github.com/googleapis/nodejs-local-auth is failing with the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/synthtool/synthtool/languages/node.py", line 319, in <module>
    owlbot_main()
  File "/synthtool/synthtool/languages/node.py", line 286, in owlbot_main
    default_version = json.load(open(".repo-metadata.json", "rt"))["default_version"]
KeyError: 'default_version'
```

This is because OwlBot was added to a repo that does not have generated code (_just so we could take advantage of the shared templates._)

This is behavior I think is worth supporting, so that we can retire synthtool entirely.

2021-04-02 18:09 UTC, sofisl approved these changes

2021-04-05 19:38 UTC, SurferJeffAtGoogle requested changes
The path through this function becomes hard to follow.  I'd rather leave a simple owlbot.py behind than

2021-04-05 19:38 UTC, SurferJeffAtGoogle commented on synthtool/languages/node.py
> +    templates_only = json.load(open(".repo-metadata.json", "rt")).get(
We could instead inspect .OwlBot.yaml to see if there are any copies, and avoid adding another field to .repo-metadata.json.

2021-04-05 19:38 UTC, SurferJeffAtGoogle commented on synthtool/languages/node.py
> +        common_templates = gcp.CommonTemplates(template_path)
I find it hard to trace the path through this function with the nested if statements.  We could reduce the nested if depth by one by structuring it like this:

```py
if templates_only:
  versions = []
  default_version = None
elif staging.is_dir():
  ...
else:
  ...

common_templates = gcp.CommonTemplates(template_path)
...
```

2021-04-06 20:41 UTC, closed without merging