build: make ci testing conditional on engines field in package.json
googleapis/synthtool pull request #1418
Opened 2022-04-13 01:26 UTC by sofisl

Deleting Node 10 configs here, but we will also have to delete them in each repo.

2022-04-13 16:51 UTC, bcoe requested changes
Looking slick to me, left a recommendation for a test and a tiny refactor.

2022-04-13 23:03 UTC, sofisl commented on synthtool/languages/node.py
> +        data["engine"] = data["engines"]["node"].replace(">=", "").replace(".0", "")
cool, PTAL!

2022-04-14 14:52 UTC, bcoe commented on synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
> +        node: [{{metadata['engine'] | int}}, {{metadata['engine'] | int+2}}, {{metadata['engine'] | int+4}}, {{metadata['engine'] | int+6}}]
Slight problem, node 18 won't exist for another 20 days.

Let's just make this `{{metadata['engine'] | int}}, {{metadata['engine'] | int+2}}, {{metadata['engine'] | int+4}}` for now, and in a couple months we can add Node 18.

2022-04-14 14:53 UTC, bcoe commented on tests/test_node.py
> +
```suggestion
```

2022-04-14 14:54 UTC, bcoe commented on synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
> +        node: [{{metadata['engine'] | int}}, {{metadata['engine'] | int+2}}, {{metadata['engine'] | int+4}}, {{metadata['engine'] | int+6}}]
```suggestion
        node: [{{metadata['engine'] | int}}, {{metadata['engine'] | int+2}}, {{metadata['engine'] | int+4}}]
```

2022-04-14 14:55 UTC, bcoe commented on tests/fixtures/node_templates/standard/package.json
> +
```suggestion
```

2022-04-14 14:56 UTC, bcoe approved these changes

2022-04-14 17:35 UTC, merged