feat(python): Detecting tests in nested directories.
googleapis/synthtool pull request #1572
Opened 2022-09-08 15:11 UTC by m-strzelczyk

Sometimes tests are not on the same level as the current working directory. PyTest doesn't have a problem with this, neither should we.

2022-09-08 15:30 UTC, parthea approved these changes

2022-09-09 17:02 UTC, parthea requested changes
Please could you revert this commit https://github.com/googleapis/synthtool/pull/1572/commits/f1140c0c99459a40d1d1a61b6cc52a613a6a3b11  ? Only the first commit is needed based on my testing .

2022-09-12 13:18 UTC, m-strzelczyk commented
> Please could you revert this commit [f1140c0](https://github.com/googleapis/synthtool/commit/f1140c0c99459a40d1d1a61b6cc52a613a6a3b11) ? Only the first commit is needed based on my testing. Please could you share more information?

According to my tests, the version I suggest with that commit works better, finds tests that are nested deeper. Please see this short test script:

```python
import tempfile
import glob
import os
import pathlib

if __name__ == '__main__':
    tmp_dir = tempfile.mkdtemp()
    os.chdir(tmp_dir)
    pathlib.Path('l1/l2/tests/some_test.txt').mkdir(parents=True, exist_ok=True)
    pathlib.Path('l1/l2/something_else').mkdir(parents=True, exist_ok=True)
    pathlib.Path('l1-bis/tests').mkdir(parents=True, exist_ok=True)

    print('glob.glob("tests"): ', glob.glob("tests"))
    print('glob.glob("**/tests"): ', glob.glob("**/tests"))
    print('glob.glob("tests", recursive=True): ', glob.glob("tests", recursive=True))
    print('glob.glob("**/tests", recursive=True): ', glob.glob("**/tests", recursive=True))
```

My output:
```
glob.glob("tests"):  []
glob.glob("**/tests"):  ['l1-bis/tests']
glob.glob("tests", recursive=True):  []
glob.glob("**/tests", recursive=True):  ['l1-bis/tests', 'l1/l2/tests']
```

2022-09-13 15:02 UTC, parthea approved these changes
LGTM

2022-09-13 15:02 UTC, merged