feat: updates python and dependency versions
googleapis/synthtool pull request #1826
Opened 2023-07-06 13:23 UTC by chalmerlowe

Updates the Python versions and versions of several of the primary tools listed in the install commands.

2023-07-06 14:04 UTC, parthea commented
The `gcr.io/cloud-devrel-kokoro-resources/python:latest` needs to be updated with python 3.7/3.11 before merging. We should also add a line to configure nox to error on missing interpreters so that the build fails. See https://github.com/googleapis/python-language/blob/main/noxfile.py#L75

```
nox > Running session lint-3.7
nox > Session lint-3.7 skipped: Python interpreter 3.7 not found.
nox > Running session lint-3.11
nox > Session lint-3.11 skipped: Python interpreter 3.11 not found.
nox > Running session test-3.7
nox > Session test-3.7 skipped: Python interpreter 3.7 not found.
nox > Running session test-3.11
nox > Session test-3.11 skipped: Python interpreter 3.11 not found.
```

2023-07-06 15:04 UTC, chalmerlowe commented
So now I am perplexed.
The `python` Docker image is based off of the `python-base` Docker image. 
When the tests for this are run, I wonder if the kokoro CI presubmit is running using an older version of the `python` Docker image and thus will never see the Python interpreters until the `python` image gets rebuilt properly.

Do we have a chicken and the egg situation here?

Can we force each of the python images to be built so that the daisy chain can function properly? OR am I just missing something cause computers are hard?

2023-07-06 16:00 UTC, parthea commented
In the python base image, it looks like we only have python 2.7 and python 3.9
https://github.com/googleapis/testing-infra-docker/blob/main/python/cloud-devrel-kokoro-resources/python-base/Dockerfile#L97.

We'll need to update the python base Dockerfile to something like this to install all versions
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.kokoro/docker/Dockerfile#L120

We should also modify the Dockerfile to test all versions like we do here
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.kokoro/docker/Dockerfile#L166

2023-07-06 16:30 UTC, parthea requested changes
See comments

2023-07-07 14:51 UTC, chalmerlowe commented
> In the python base image, it looks like we only have python 2.7 and python 3.9 https://github.com/googleapis/testing-infra-docker/blob/main/python/cloud-devrel-kokoro-resources/python-base/Dockerfile#L97.

This has been updated but is waiting on a PR merge.
https://github.com/googleapis/testing-infra-docker/pull/301/files/cf5264f6b4e5a1961b1a3311ce6004ccb7c83fb8#
> 
> We'll need to update the python base Dockerfile to something like this to install all versions https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.kokoro/docker/Dockerfile#L120

See note above.

> 
> We should also modify the Dockerfile to test all versions like we do here https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.kokoro/docker/Dockerfile#L166

Will do.

2023-07-13 16:55 UTC, chalmerlowe commented
@alicejli / @parthea 

This PR should fix the issue that you are referencing: https://github.com/googleapis/testing-infra-docker/pull/301

It updates `python-base` docker image with a wide variety of interpreters.
`python-base` is the foundation of the `python` docker image, so those interpreters should carry into `python`.
That and this PR should ensure that the correct python interpreters are present and should eliminate the error above.

PR #301 is waiting on review.
And should be implemented before this one (note, it will take a while for the docker image to update once that PR is pushed through ... could be up to an hour and 15 minutes).

2023-07-19 14:11 UTC, chalmerlowe commented
Tried to update python-base with `libffi-dev`.
Once that goes through the process and is built, we can try this PR again to see if it passes tests.

2023-07-26 14:24 UTC, chalmerlowe commented
For some unknown reason, while the `latest` Python image is being used it is not the correct image.

The image tagged `latest` was the most recent image that was uploaded to the image repository, but it is not the most recently created image.

Got a question in the Google Chat to get some clarity on what might have caused this discrepancy/how to avoid it. Will need to retag the images and try to rerun the checks on this repo.

2023-07-28 16:12 UTC, chalmerlowe commented on noxfile.py
> +    session.install('mypy==1.4.1', 'flake8', 'black==23.3.0')
```suggestion
    session.install('mypy==0.971', 'flake8', 'black==23.3.0')
```

2023-07-28 16:24 UTC, chalmerlowe commented on noxfile.py
> +    session.install('mypy==0.971', 'flake8', 'black==23.3.0')
```suggestion
    session.install('mypy==0.900', 'flake8', 'black==23.3.0')
```

2023-07-28 16:36 UTC, chalmerlowe commented on noxfile.py
> +    session.install('mypy==0.900', 'flake8', 'black==23.3.0')
```suggestion
    session.install('mypy==0.800', 'flake8', 'black==23.3.0')
```

2023-07-28 16:57 UTC, chalmerlowe commented on noxfile.py
> +PYTHON_VERSIONS = ['3.7', '3.11']
```suggestion
PYTHON_VERSIONS = ['3.8', '3.10']
```

2023-07-28 17:07 UTC, chalmerlowe commented on noxfile.py
> +    session.install('mypy==0.800', 'flake8', 'black==23.3.0')
```suggestion
    session.install('mypy==0.790', 'flake8', 'black==23.3.0')
```

2023-07-28 18:27 UTC, parthea approved these changes

2023-07-28 18:28 UTC, merged