BOM with gradle
googleapis/synthtool pull request #890
Opened 2020-12-23 18:43 UTC by elharo

2020-12-23 19:20 UTC, chingor13 commented
We collect some common metadata in the [java specific templates helper](https://github.com/googleapis/synthtool/blob/6b026e1443948dcfc0b9e3289c85e940eb70f694/synthtool/languages/java.py#L346-L348). 

It should be available as `metadata['latest_bom_version']`.

2020-12-23 20:59 UTC, elharo commented
Thanks. That's exactly what I needed. It should be ready for review now.

2021-01-05 17:21 UTC, SurferJeffAtGoogle reviewed
LGTM.  I leave it to @chingor13 to approve.

2021-01-05 18:10 UTC, chingor13 requested changes

2021-01-05 18:10 UTC, chingor13 commented on synthtool/gcp/templates/java_library/README.md
> +implementation platform('com.google.cloud:libraries-bom:metadata['latest_bom_version']')
```suggestion
implementation platform('com.google.cloud:libraries-bom:{{metadata['latest_bom_version']}}')
```

Need to use jinja template variable tags

2021-01-05 18:13 UTC, elharo reviewed
done

2021-01-05 18:17 UTC, chingor13 approved these changes

2021-01-05 18:17 UTC, merged