chore: make updates to toc.yml before upload
googleapis/synthtool pull request #960
Opened 2021-02-24 18:20 UTC by eaball35

- adding README as overview
- sorting toc on package
- adding product hierarchy
- script cleanup

2021-02-24 18:22 UTC, eaball35 commented
Tested these changes out in single library (on branch in java-memcache) and is working correctly as expected

2021-02-24 19:11 UTC, eaball35 commented
b/181142127
b/179920619
b/179799230

2021-02-25 01:10 UTC, chingor13 requested changes
Is this testable anywhere? Ideally, we can test this script (perhaps make this part of synthtool)

2021-02-25 01:10 UTC, chingor13 commented on synthtool/gcp/templates/java_library/.kokoro/release/prepare_docs.py
> +# Copyright 2021 Google Inc.
```suggestion
# Copyright 2021 Google LLC
```

2021-03-01 19:14 UTC, chingor13 requested changes
The CI failure is because the python template is being compiled in-place, then the template engine is confused because it sees a new compiled.py file and tries to load it as a utf-8 file (which it's not).

From an offline chat, we decided the python script belongs in a single place in a python library (gcp-docuploader/publisher perhaps?) rather than as a standalone python file in 100+ repos.

2021-03-01 21:56 UTC, eaball35 commented
Moving this out of synthtool and into docuploader instead https://github.com/googleapis/docuploader/pull/58

2021-03-01 21:56 UTC, closed without merging